<?php

namespace AppBundle\Repository;

/**
 * Commentaire_QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_QuizzRepository extends \Doctrine\ORM\EntityRepository
{
}
