<?php

namespace AppBundle\Repository;

/**
 * Commentaire_EnqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commentaire_EnqueteRepository extends \Doctrine\ORM\EntityRepository
{
}
