<?php

namespace AppBundle\Repository;

/**
 * Question_SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question_SondageRepository extends \Doctrine\ORM\EntityRepository
{
}
