<?php

namespace AppBundle\Repository;

/**
 * Question_QuizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question_QuizzRepository extends \Doctrine\ORM\EntityRepository
{
}
