<?php

namespace AppBundle\Repository;

/**
 * Reponse_SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reponse_SequenceRepository extends \Doctrine\ORM\EntityRepository
{
}
