<?php

namespace AppBundle\Repository;

/**
 * Sondage_CompletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sondage_CompletRepository extends \Doctrine\ORM\EntityRepository
{
}
